[General]
key_pmi=8624292574
key_pmi_invite_msg="K.M. Merajul Arefin Pial is inviting you to a scheduled Zoom meeting.\r\n\r\nTopic: K.M. Merajul Arefin Pial's Personal Meeting Room\r\n\r\nJoin Zoom Meeting\r\nhttps://zoom.us/j/8624292574?pwd=SkZLVERHeVo3NzBFdFR5VjdiSHdpQT09\r\n\r\nMeeting ID: 862 429 2574\r\nPasscode: 1UT5Sg\r\n\r\n"
